# @format

name: "Upload Yaml to SSM Parameter Store"
description: "Upload to SSM Parameter Store from YAML file or directory"
inputs:
    aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
    aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true
    aws_region:
        description: "AWS Region"
        required: true
    aws_account_id:
        description: "AWS Account"
        required: true
    prefix:
        description: "Prefix for SSM Parameter Store"
        required: true
    path:
        description: "Path to Directory or YAML file"
        required: true
    clean:
        description: "Optionally removes unknown parameters found in the prefix"
        required: false
        default: false
    batch_count:
        description: "Number of parameters to upload before pausing"
        required: false
        default: 20
    pause_time:
        description: "Number of milliseconds to pause after uploading the number of parameters specified in pause_count"
        required: false
        default: 1500
    max_save_attempts:
        description: "Number of times to attempt to save a parameter before giving up"
        required: false
        default: 5
outputs:
    time: # output will be available to future steps
        description: "The current time after completion"
    parameters:
        description: "The number of parameters found in the YAML file or directory"
    existing:
        description: "The number of parameters already existing"
    created:
        description: "The number of parameters created"
    updated:
        description: "The number of parameters updated"
    deleted:
        description: "The number of parameters deleted"
    unchanged:
        description: "The number of parameters unchanged"
runs:
    using: "node16"
    main: "dist/index.js"
branding:
    icon: "arrow-up"
    color: "blue"
